project:
  type: website

website:
  title: "Sebastian Hellmann's website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - dynaViTE_model.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



